import { ClanDetails, ClanId, CatAppearance, HerbItem, Prophecy } from '../types/game';

export const CLAN_LORE: Record<string, ClanDetails> = {
  ThunderClan: {
    id: 'ThunderClan' as ClanId,
    name: 'ThunderClan',
    motto: 'Courage beneath the canopy, fierce as the storm.',
    description: 'Masters of dense deciduous oak woodlands and thick undergrowth. Renowned for their bravery, muscular stalks, and unwavering loyalty.',
    territoryName: 'Sunlit Oak Forest & Ravine Camp',
    leaderName: 'BrambleStar',
    deputyName: 'RowanClaw',
    medCatName: 'FernWhisper',
    primaryColor: '#e07a22',
    badgeIcon: '⚡',
    freshKillCount: 24,
  },
  RiverClan: {
    id: 'RiverClan' as ClanId,
    name: 'RiverClan',
    motto: 'Swift as the rapids, graceful beneath the waves.',
    description: 'Sleek, water-loving cats who live alongside winding riverbanks and reed beds. Renowned for swimming prowess, sleek coats, and fish hunting.',
    territoryName: 'Glimmering Reeds & Island Camp',
    leaderName: 'RippleStar',
    deputyName: 'OtterSplash',
    medCatName: 'WillowShine',
    primaryColor: '#3b82f6',
    badgeIcon: '🌊',
    freshKillCount: 21,
  },
  ShadowClan: {
    id: 'ShadowClan' as ClanId,
    name: 'ShadowClan',
    motto: 'Silent as pine needles, striking in the dark.',
    description: 'Stealthy, cunning felines who hunt amidst dark pine groves, marshy pools, and moonlit bogs. Feared for night ambushes and unmatched silence.',
    territoryName: 'Pine Shadows & Marsh Hollow',
    leaderName: 'NightStar',
    deputyName: 'ViperStrike',
    medCatName: 'SagePool',
    primaryColor: '#8b5cf6',
    badgeIcon: '🌙',
    freshKillCount: 18,
  },
  WindClan: {
    id: 'WindClan' as ClanId,
    name: 'WindClan',
    motto: 'Fast as the gale, free beneath the open sky.',
    description: 'Slender, long-legged runners who roam open heather moorlands and rolling hills. Quickest hunters of swift moor rabbits.',
    territoryName: 'Whispering Moor & Gorge Camp',
    leaderName: 'GaleStar',
    deputyName: 'FalconPounce',
    medCatName: 'HeatherBreeze',
    primaryColor: '#10b981',
    badgeIcon: '🍃',
    freshKillCount: 20,
  },
  Loner: {
    id: 'Loner' as ClanId,
    name: 'Loner & Rogue',
    motto: 'Bound to no clan law, master of my own paws.',
    description: 'Independent cats who roam outside Clan boundaries, finding shelter in abandoned two-leg nests, rocky cliffs, and forgotten hollows.',
    territoryName: 'Neutral Borderlands & Two-leg Ruins',
    leaderName: 'None',
    deputyName: 'None',
    medCatName: 'None',
    primaryColor: '#94a3b8',
    badgeIcon: '🐾',
    freshKillCount: 8,
  },
  // Compatibility aliases
  ThunderOak: {
    id: 'ThunderClan' as ClanId,
    name: 'ThunderClan',
    motto: 'Courage beneath the canopy, fierce as the storm.',
    description: 'Masters of dense deciduous oak woodlands and thick undergrowth. Renowned for their bravery, muscular stalks, and unwavering loyalty.',
    territoryName: 'Sunlit Oak Forest & Ravine Camp',
    leaderName: 'BrambleStar',
    deputyName: 'RowanClaw',
    medCatName: 'FernWhisper',
    primaryColor: '#e07a22',
    badgeIcon: '⚡',
    freshKillCount: 24,
  },
  RiverMist: {
    id: 'RiverClan' as ClanId,
    name: 'RiverClan',
    motto: 'Swift as the rapids, graceful beneath the waves.',
    description: 'Sleek, water-loving cats who live alongside winding riverbanks and reed beds. Renowned for swimming prowess, sleek coats, and fish hunting.',
    territoryName: 'Glimmering Reeds & Island Camp',
    leaderName: 'RippleStar',
    deputyName: 'OtterSplash',
    medCatName: 'WillowShine',
    primaryColor: '#3b82f6',
    badgeIcon: '🌊',
    freshKillCount: 21,
  },
  ShadowPines: {
    id: 'ShadowClan' as ClanId,
    name: 'ShadowClan',
    motto: 'Silent as pine needles, striking in the dark.',
    description: 'Stealthy, cunning felines who hunt amidst dark pine groves, marshy pools, and moonlit bogs.',
    territoryName: 'Pine Shadows & Marsh Hollow',
    leaderName: 'NightStar',
    deputyName: 'ViperStrike',
    medCatName: 'SagePool',
    primaryColor: '#8b5cf6',
    badgeIcon: '🌙',
    freshKillCount: 18,
  },
  WindBreeze: {
    id: 'WindClan' as ClanId,
    name: 'WindClan',
    motto: 'Fast as the gale, free beneath the open sky.',
    description: 'Slender, long-legged runners who roam open heather moorlands and rolling hills.',
    territoryName: 'Whispering Moor & Gorge Camp',
    leaderName: 'GaleStar',
    deputyName: 'FalconPounce',
    medCatName: 'HeatherBreeze',
    primaryColor: '#10b981',
    badgeIcon: '🍃',
    freshKillCount: 20,
  },
};

export const DEFAULT_APPEARANCE: CatAppearance = {
  bodyType: 'adult',
  furStyle: 'medium',
  primaryColor: '#c8763e', // ginger / golden brown
  secondaryColor: '#fde68a', // creamy underbelly / markings
  underbellyColor: '#fffbeb',
  markingType: 'mackerel_tabby',
  eyeColorLeft: '#10b981', // emerald green
  eyeColorRight: '#10b981',
  isHeterochromia: false,
  eyeState: 'normal',
  muzzleLength: 1.0,
  muzzleShape: 'normal',
  earSize: 1.0,
  earShape: 'normal',
  earTufts: false,
  tailLength: 1.0,
  tailThickness: 1.0,
  legLength: 1.0,
  pawSize: 1.0,
  bodyScale: 1.0,
  accessory: 'none',
  scar: 'none',
  aura: 'none',
};

export const COLOR_PALETTE = {
  fur: [
    { name: 'Pitch Black', hex: '#18181b' },
    { name: 'Smoky Charcoal', hex: '#334155' },
    { name: 'Silver Gray', hex: '#94a3b8' },
    { name: 'Blue-Gray (RiverClan Silver)', hex: '#64748b' },
    { name: 'Pure Snow', hex: '#f8fafc' },
    { name: 'Warm Cream', hex: '#fef3c7' },
    { name: 'Sandy Beige', hex: '#d97706' },
    { name: 'Golden Ginger', hex: '#ea580c' },
    { name: 'Flame Red', hex: '#dc2626' },
    { name: 'Tawny Amber', hex: '#b45309' },
    { name: 'Rich Chestnut', hex: '#78350f' },
    { name: 'Dark Chocolate', hex: '#451a03' },
    { name: 'Russet Cinnamon', hex: '#9a3412' },
    { name: 'Smoky Ash', hex: '#475569' },
    { name: 'Pale Fawn', hex: '#fed7aa' },
    { name: 'Sable Brown', hex: '#3b1d07' },
  ],
  eyes: [
    { name: 'Forest Emerald', hex: '#10b981' },
    { name: 'Mint Jade', hex: '#34d399' },
    { name: 'Sapphire Blue', hex: '#2563eb' },
    { name: 'Ice Cyan', hex: '#38bdf8' },
    { name: 'Pale Sky Blue', hex: '#93c5fd' },
    { name: 'Sun Amber', hex: '#f59e0b' },
    { name: 'Golden Honey', hex: '#eab308' },
    { name: 'Pure Gold', hex: '#fbbf24' },
    { name: 'Copper Flame', hex: '#f97316' },
    { name: 'Blazing Orange', hex: '#ea580c' },
    { name: 'Deep Violet', hex: '#a855f7' },
    { name: 'Pale Hazel', hex: '#84cc16' },
    { name: 'Smoky Slate Gray', hex: '#64748b' },
    { name: 'Blood Ruby', hex: '#e11d48' },
  ],
};

export const CAT_NAME_PREFIXES = [
  'Bramble', 'Oak', 'Shadow', 'River', 'Storm', 'Golden', 'Silver', 'Flame', 'Frost',
  'Night', 'Rowan', 'Fern', 'Alder', 'Hawk', 'Falcon', 'Raven', 'Eagle', 'Thistle',
  'Moss', 'Clover', 'Willow', 'Birch', 'Ash', 'Cedar', 'Pebble', 'Swift', 'Leopard',
  'Lion', 'Tiger', 'Cloud', 'Mist', 'Dawn', 'Dusk', 'Ember', 'Fox', 'Badger', 'Wolf',
];

export const CAT_NAME_SUFFIXES = [
  'claw', 'fur', 'pelt', 'tail', 'heart', 'storm', 'stride', 'whisper', 'watcher',
  'fall', 'flight', 'shine', 'song', 'pool', 'leap', 'pounce', 'breeze', 'feather',
  'wing', 'frost', 'shade', 'fang', 'gaze', 'step', 'branch', 'blaze', 'stream',
];

export const INITIAL_HERBS: HerbItem[] = [
  {
    id: 'marigold-1',
    type: 'marigold',
    name: 'Marigold Blossom',
    description: 'Bright golden petals that stop infection and disinfect bleeding claw wounds.',
    cures: 'Cures Infection & Bleeding',
    quantity: 2,
  },
  {
    id: 'dock-1',
    type: 'dock',
    name: 'Dock Leaf',
    description: 'Broad soothing leaves chewed to soothe stinging nettles and abrasive scratches.',
    cures: 'Soothes Scratches & Stings',
    quantity: 3,
  },
  {
    id: 'poppy-1',
    type: 'poppy_seed',
    name: 'Poppy Seeds',
    description: 'Small dark seeds that induce soothing sleep and ease intense physical pain.',
    cures: 'Relieves Severe Pain & Restores Stamina',
    quantity: 4,
  },
  {
    id: 'horsetail-1',
    type: 'horsetail',
    name: 'Horsetail Reed',
    description: 'Tall fibrous stalks crushed into a poultice to bind sprained paws and broken joints.',
    cures: 'Mends Sprains & Limping',
    quantity: 2,
  },
  {
    id: 'catmint-1',
    type: 'catmint',
    name: 'Wild Catmint',
    description: 'Fragrant rare leafy herb that instantly revitalizes weary spirits and cures greencough.',
    cures: 'Restores Max Health & Vitality',
    quantity: 1,
  },
];

export const PROCEDURAL_PROPHECIES: Prophecy[] = [
  {
    id: 'prophecy-1',
    title: 'The Shadows in the Brambles',
    verses: [
      'When the river runs silver beneath the crescent moon,',
      'The thorn will strike before the blossom can bloom.',
      'Only the heart born of storm and fire',
      'Can guide the four clans from the encroaching mire.',
    ],
    ancestorGiver: 'SilverStar of Ancient StarClan',
    receivedAt: 'The Sacred Moonpool Sanctuary',
    meaning: 'A dark conflict threatens the borderlands; courage and unity must triumph over ancient blood-feuds.',
  },
  {
    id: 'prophecy-2',
    title: 'The Whisper of Nine Sparks',
    verses: [
      'Nine lives pledged to the sacred oak,',
      'Nine spirits answer when the thunder spoke.',
      'Beware the shadow that trains in sleep,',
      'For promises made in darkness are bitter to keep.',
    ],
    ancestorGiver: 'GoldenFeather, Founder of ThunderOak',
    receivedAt: 'The Silverpelt Gathering Ground',
    meaning: 'The Dark Forest is reaching into the dreams of ambitious warriors; leaders must watch their apprentices closely.',
  },
  {
    id: 'prophecy-3',
    title: 'The Clear Stream Awakening',
    verses: [
      'Water shall quench what fire ignited,',
      'When long-divided kin are once more reunited.',
      'Seek the herb on the highest stone crest,',
      'To put the weeping sickness to final rest.',
    ],
    ancestorGiver: 'RipplePool, Ancient Medicine Healer',
    receivedAt: 'The Moonpool Reflections',
    meaning: 'Medicine cats are guided towards the rare high-peak Catmint to heal deep clan wounds.',
  },
];
